// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD7m56nV2HRAv4gwgFgf42J_iN7lGgsNw',
    appId: '1:621439544509:web:04704179b1f889a3f19bd4',
    messagingSenderId: '621439544509',
    projectId: 'practise-d5791',
    authDomain: 'practise-d5791.firebaseapp.com',
    storageBucket: 'practise-d5791.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqBqzPTAxGCN1qqaqMD_lJcKr_IFW0OY',
    appId: '1:621439544509:android:c932101c09674f9af19bd4',
    messagingSenderId: '621439544509',
    projectId: 'practise-d5791',
    storageBucket: 'practise-d5791.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIbPMKGbWvcln4kQCo-X5TIxMQvJBxtU',
    appId: '1:621439544509:ios:4e737cc965fb7f2af19bd4',
    messagingSenderId: '621439544509',
    projectId: 'practise-d5791',
    storageBucket: 'practise-d5791.appspot.com',
    iosBundleId: 'com.example.practise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIbPMKGbWvcln4kQCo-X5TIxMQvJBxtU',
    appId: '1:621439544509:ios:4e737cc965fb7f2af19bd4',
    messagingSenderId: '621439544509',
    projectId: 'practise-d5791',
    storageBucket: 'practise-d5791.appspot.com',
    iosBundleId: 'com.example.practise',
  );
}
